### ISSUE TITLE
Can not import composite in my server host

### ISSUE THREAD

**Issue by zelokuo** [mkurop/composite-measure#1]
Dear authors, 
   Recently, I try to install your great package on my lab's server computer in which I do not have sudo /root accounts. Therefore, I used  this command to copy head files to $HOME/opt/include/, cuz, without  sudo command it can not copy head files to "/usr/local/include/"
"cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt ."
After installed, I try 
from composite.composite_measure import composite
I got 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "composite_measure.pyx", line 1, in init composite_measure
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
I will appreciate your reply.

**Comment by zelokuo** [comment]
by the way, it works well on my pc with sudo command
